FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src
COPY FileAnalysisService/*.csproj ./FileAnalysisService/
RUN dotnet restore FileAnalysisService/FileAnalysisService.csproj
COPY . .
WORKDIR /src/FileAnalysisService
RUN dotnet publish -c Release -o /app/publish

FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS runtime
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "FileAnalysisService.dll"]